### ISSUE TITLE
TypeError: Missing argument 'scope' for MetricInstance

### ISSUE THREAD

**Issue by raymerta** [Agnostic-IO-Analysis/Darshan2OTF2#1]
Hi, I had a problem running `python3 darshan_to_otf2.py -o output darshan_file`. 

Here's the output: 
```
Traceback (most recent call last):
  File "/Darshan2OTF2/darshan_to_otf2.py", line 157, in <module>
    main()
  File "/Darshan2OTF2/darshan_to_otf2.py", line 153, in main
    write_oft2_trace(fp_in, fp_out, timer_res)
  File "/Darshan2OTF2/darshan_to_otf2.py", line 128, in write_oft2_trace
    metric_instance = trace.definitions.metric_instance(metric_class=metric_classes.get(counter_key),
  File "/perf-tools/otf2/3.0/lib/python3.9/site-packages/otf2/registry.py", line 369, in metric_instance
    return self._metrics.get(*args, _type=definitions.MetricInstance, **kwargs)
  File "/perf-tools/otf2/3.0/lib/python3.9/site-packages/otf2/registry.py", line 97, in get
    key = t._new_key(self, *args, **kwargs)
  File "/perf-tools/otf2/3.0/lib/python3.9/site-packages/otf2/definitions.py", line 244, in _new_key
    return cls(registry, None, *args, **kwargs)._key
  File "/perf-tools/otf2/3.0/lib/python3.9/site-packages/otf2/definitions.py", line 697, in __init__
    raise TypeError("Missing argument 'scope' for MetricInstance.")
TypeError: Missing argument 'scope' for MetricInstance.
```

**Comment by blastmaster** [comment]
I think this problem occurs when the location provided as metric scope is -1. I provided a workaround for that with [a8c685f](https://github.com/Agnostic-IO-Analysis/Darshan2OTF2/commit/a8c685f5d925a20df839ee0224fb57cce77bc6cb).
